/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScrollingIndexRouteImport } from './routes/scrolling/index'
import { Route as PointingIndexRouteImport } from './routes/pointing/index'
import { Route as ClassificationIndexRouteImport } from './routes/classification/index'

const ScrollingIndexRoute = ScrollingIndexRouteImport.update({
  id: '/scrolling/',
  path: '/scrolling/',
  getParentRoute: () => rootRouteImport,
} as any)
const PointingIndexRoute = PointingIndexRouteImport.update({
  id: '/pointing/',
  path: '/pointing/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificationIndexRoute = ClassificationIndexRouteImport.update({
  id: '/classification/',
  path: '/classification/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/classification': typeof ClassificationIndexRoute
  '/pointing': typeof PointingIndexRoute
  '/scrolling': typeof ScrollingIndexRoute
}
export interface FileRoutesByTo {
  '/classification': typeof ClassificationIndexRoute
  '/pointing': typeof PointingIndexRoute
  '/scrolling': typeof ScrollingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/classification/': typeof ClassificationIndexRoute
  '/pointing/': typeof PointingIndexRoute
  '/scrolling/': typeof ScrollingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/classification' | '/pointing' | '/scrolling'
  fileRoutesByTo: FileRoutesByTo
  to: '/classification' | '/pointing' | '/scrolling'
  id: '__root__' | '/classification/' | '/pointing/' | '/scrolling/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ClassificationIndexRoute: typeof ClassificationIndexRoute
  PointingIndexRoute: typeof PointingIndexRoute
  ScrollingIndexRoute: typeof ScrollingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scrolling/': {
      id: '/scrolling/'
      path: '/scrolling'
      fullPath: '/scrolling'
      preLoaderRoute: typeof ScrollingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pointing/': {
      id: '/pointing/'
      path: '/pointing'
      fullPath: '/pointing'
      preLoaderRoute: typeof PointingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classification/': {
      id: '/classification/'
      path: '/classification'
      fullPath: '/classification'
      preLoaderRoute: typeof ClassificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ClassificationIndexRoute: ClassificationIndexRoute,
  PointingIndexRoute: PointingIndexRoute,
  ScrollingIndexRoute: ScrollingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
